# Generated by Django 3.0.7 on 2020-08-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=12)),
                ('desc', models.TextField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
